# Generated by Django 5.1.2 on 2024-11-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(db_column='nome', max_length=128)),
                ('genero', models.CharField(choices=[('MC', 'Mulher cisgênero'), ('MTG', 'Mulher transgênero'), ('HC', 'Homem cisgênero'), ('HTGHomem transgênero', 'Htg'), ('GNB', 'Gênero não-binário'), ('A', 'Agênero'), ('GF', 'Gênero-fluido'), ('B', 'Bigênero'), ('MTS', 'Mulher transexual'), ('HTS', 'Homem transexual'), ('P', 'Poligênero'), ('O', 'Outros'), ('ND', 'Não declarado')], db_column='genero', default='ND', max_length=20)),
                ('has_esgoto', models.BooleanField(db_column='has_esgoto', default=False)),
                ('historico_saude', models.TextField(db_column='historico_saude')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='SaneamentoInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bairro', models.CharField(db_column='Bairro', max_length=30)),
                ('cidade', models.CharField(db_column='cidade', max_length=30)),
                ('agua_potavel', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='agua_potavel', default='N', max_length=1)),
                ('coleta_lixo', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='coleta_lixo', default='N', max_length=1)),
                ('instalacoes_sanitarias', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='instalacoes_sanitarias', default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'SaneamentoInfo',
                'verbose_name_plural': 'SaneamentoInfos',
            },
        ),
    ]
